=== SambaGodschynski/uiui/uiui.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "description": ""
        },
        "title": {
            "type": "string",
            "description": ""
        },
        "comment": {
            "type": "string",
            "description": "Set the characters for a line comment such as '//' or '#'. UiUi needs comments to save its meta data."
        },
        "outfile": {
            "type": "string",
            "description": ""
        },
        "template": {
            "type": "string",
            "description": ""
        },
        "render": {
            "type": "string",
            "description": ""
        },
        "placeholder": {
            "type": "string",
            "description": ""
        },
        "children": {
            "type": "array",
            "description": "",
            "items": {
                "$ref": "#/definitions/childNode"
            }
        }
    },
    "required": [
        "outfile",
        "comment"
    ],
    "definitions": {
        "childNode": {
            "type": "object",
            "required": [],
            "properties": {
                "id": {
                    "type": "string",
                    "description": ""
                },
                "title": {
                    "type": "string",
                    "description": ""
                },
                "render": {
                    "type": "string",
                    "description": ""
                },
                "placeholder": {
                    "type": "string",
                    "description": ""
                },
                "direction": {
                    "type": "string",
                    "description": ""
                },
                "ctrl": {
                    "type": "string",
                    "description": "",
                    "enum": ["slider"]
                },
                "minValue": {
                    "type": "number",
                    "description": ""
                },
                "maxValue": {
                    "type": "number",
                    "description": ""
                },
                "step": {
                    "type": "number",
                    "description": ""
                },
                "defaultValue": {
                    "description": ""
                },
                "postProcess": {
                    "type": "string",
                    "description": ""
                },
                "children": {
                    "type": "array",
                    "description": "",
                    "items": {
                        "$ref": "#/definitions/childNode"
                    }
                }
            }
        }
    }
}

=== SambaGodschynski/uiui/first.without-template.uiui.json
{
    "title": "My First UiUi Panel",
    "comment": "--",
    "outfile": "./first.uiui.rendered",
    "render": "-- this is a render output of uiui\n----------------------------------",
    "children": [
        {
            "direction": "column",
            "children": [
                {
                    "id": "value1",
                    "title": "Value 1",
                    "ctrl": "slider",
                    "render": "v1 = #value1",
                    "minValue": 0,
                    "maxValue": 5,
                    "step": 1,
                    "defaultValue": 4,
                    "postProcess": "value/2"
                },
                {
                    "title": "Parameter Group",
                    "render": "v2 = #value2\nv3 = #value3",
                    "children": [
                        {
                            "id": "value2",
                            "title": "Value 1",
                            "ctrl": "slider"
                        },
                        {
                            "id": "value3",
                            "title": "Value 2",
                            "ctrl": "slider"
                        }
                    ]
                }
            ]
        }
    ]
}
